# Generated by Django 5.1.4 on 2026-09-09 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escales", "0001_initial"),
        ("kpi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("kpi_seuil", "KPI hors seuil"),
                            ("congestion", "Congestion détectée"),
                            ("retard", "Retard escale"),
                            ("occupation", "Taux occupation élevé"),
                            ("attente_longue", "Temps d'attente excessif"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "niveau_gravite",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("avertissement", "Avertissement"),
                            ("critique", "Critique"),
                        ],
                        default="avertissement",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "valeur_declenchante",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "date_declenchement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acquittee", "Acquittée"),
                            ("resolue", "Résolue"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                (
                    "escale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="escales.escale",
                        verbose_name="Escale concernée",
                    ),
                ),
                (
                    "seuil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="kpi.seuilalerte",
                        verbose_name="Seuil déclencheur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "db_table": "alerte",
                "ordering": ["-date_declenchement"],
            },
        ),
        migrations.CreateModel(
            name="UtilisateurAlerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "statut_lecture",
                    models.CharField(
                        choices=[("non_lu", "Non lu"), ("lu", "Lu")],
                        default="non_lu",
                        max_length=10,
                    ),
                ),
                (
                    "alerte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alerts.alerte",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_utilisateur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification d'alerte",
                "db_table": "utilisateur_alerte",
            },
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["statut"], name="alerte_statut_22029f_idx"),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(
                fields=["niveau_gravite"], name="alerte_niveau__6a3ed8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(
                fields=["date_declenchement"], name="alerte_date_de_0cede4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="utilisateuralerte",
            unique_together={("utilisateur", "alerte")},
        ),
    ]
