# Generated by Django 5.1.4 on 2026-08-19 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Nom du fichier ou de la source importée",
                        max_length=255,
                    ),
                ),
                ("date_import", models.DateTimeField(auto_now_add=True)),
                ("nb_lignes_lues", models.PositiveIntegerField(default=0)),
                ("nb_lignes_chargees", models.PositiveIntegerField(default=0)),
                ("nb_lignes_rejetees", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("succes", "Succès"),
                            ("partiel", "Partiel (avec erreurs)"),
                            ("echec", "Échec"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                ("erreurs", models.JSONField(blank=True, default=list)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'import",
                "verbose_name_plural": "Journaux d'import",
                "ordering": ["-date_import"],
            },
        ),
    ]
