# Generated by Django 6.0.7 on 2026-07-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateTimeField()),
                ('date_accostage', models.DateTimeField(blank=True, null=True)),
                ('date_appareillage', models.DateTimeField(blank=True, null=True)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('temps_attente', models.DecimalField(blank=True, decimal_places=2, help_text='en heures', max_digits=8, null=True)),
                ('temps_sejour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temps_pilotage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temps_accostage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escales', to='referentiel.agentmaritime')),
                ('date_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escales', to='referentiel.calendrier')),
                ('import_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escales', to='etl.journalimport')),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escales', to='referentiel.navire')),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escales', to='referentiel.quai')),
            ],
            options={
                'verbose_name': 'Escale',
            },
        ),
        migrations.CreateModel(
            name='Mobiliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_reelle', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ordre_intervention', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('escale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_mobilises', to='escales.escale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobilisations', to='referentiel.servicenautique')),
            ],
            options={
                'verbose_name': 'Mobilisation de service nautique',
                'verbose_name_plural': 'Mobilisations de services nautiques',
            },
        ),
        migrations.AddIndex(
            model_name='escale',
            index=models.Index(fields=['navire'], name='escales_esc_navire__8ba7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='escale',
            index=models.Index(fields=['quai'], name='escales_esc_quai_id_c90082_idx'),
        ),
        migrations.AddIndex(
            model_name='escale',
            index=models.Index(fields=['date_ref'], name='escales_esc_date_re_be0b5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobiliser',
            constraint=models.UniqueConstraint(fields=('escale', 'service'), name='uq_mobiliser_escale_service'),
        ),
    ]
