# Generated by Django 5.1.4 on 2026-09-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kpi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("journalier", "Rapport journalier"),
                            ("hebdomadaire", "Rapport hebdomadaire"),
                            ("mensuel", "Rapport mensuel"),
                            ("personnalise", "Rapport personnalisé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("periode_debut", models.DateField()),
                ("periode_fin", models.DateField()),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel (.xlsx)")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("nb_pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("taille_octets", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport",
                "verbose_name_plural": "Rapports",
                "db_table": "rapport",
                "ordering": ["-date_generation"],
            },
        ),
        migrations.CreateModel(
            name="RapportKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="kpi.kpi",
                    ),
                ),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis_inclus",
                        to="reporting.rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI du rapport",
                "db_table": "rapport_kpi",
                "unique_together": {("rapport", "kpi")},
            },
        ),
    ]
