# Generated by Django 6.0.7 on 2026-07-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMaritime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Agent maritime',
                'verbose_name_plural': 'Agents maritimes',
            },
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calendaire', models.DateField(unique=True)),
                ('mois', models.PositiveSmallIntegerField()),
                ('trimestre', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('jour_semaine', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Calendrier',
                'ordering': ['date_calendaire'],
            },
        ),
        migrations.CreateModel(
            name='CompagnieMaritime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=150)),
                ('pays', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Compagnie maritime',
                'verbose_name_plural': 'Compagnies maritimes',
            },
        ),
        migrations.CreateModel(
            name='ServiceNautique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(max_length=50)),
                ('duree_moyenne_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Service nautique',
                'verbose_name_plural': 'Services nautiques',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Terminal',
            },
        ),
        migrations.CreateModel(
            name='TypeNavire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('categorie', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Type de navire',
                'verbose_name_plural': 'Types de navire',
            },
        ),
        migrations.CreateModel(
            name='Quai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('longueur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tirant_eau_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quais', to='referentiel.terminal')),
            ],
            options={
                'verbose_name': 'Quai',
            },
        ),
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('imo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro IMO')),
                ('pavillon', models.CharField(blank=True, max_length=60)),
                ('longueur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('jauge_brute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navires', to='referentiel.compagniemaritime')),
                ('type_navire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navires', to='referentiel.typenavire')),
            ],
            options={
                'verbose_name': 'Navire',
            },
        ),
    ]
