# Generated by Django 5.1.4 on 2026-09-09 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                ("id_kpi", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=150)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("trafic", "Trafic"),
                            ("temps", "Temps"),
                            ("infrastructures", "Infrastructures"),
                            ("performance", "Performance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("unite", models.CharField(blank=True, max_length=20, null=True)),
                ("formule", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPI",
                "db_table": "kpi",
                "ordering": ["categorie", "code"],
            },
        ),
        migrations.CreateModel(
            name="SeuilAlerte",
            fields=[
                ("id_seuil", models.AutoField(primary_key=True, serialize=False)),
                (
                    "valeur_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "valeur_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "niveau_gravite",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("avertissement", "Avertissement"),
                            ("critique", "Critique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        db_column="id_kpi",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seuils",
                        to="kpi.kpi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seuil d'alerte",
                "verbose_name_plural": "Seuil d'alerte",
                "db_table": "seuil_alerte",
            },
        ),
        migrations.CreateModel(
            name="ValeurKPI",
            fields=[
                ("id_valeur", models.AutoField(primary_key=True, serialize=False)),
                ("valeur", models.DecimalField(decimal_places=3, max_digits=12)),
                ("date_calcul", models.DateTimeField(auto_now=True)),
                (
                    "date_ref",
                    models.ForeignKey(
                        db_column="id_date",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valeurs_kpi",
                        to="referentiel.calendrier",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        db_column="id_kpi",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="kpi.kpi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur de KPI",
                "verbose_name_plural": "Valeur de KPI",
                "db_table": "valeur_kpi",
                "ordering": ["-date_ref", "kpi"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kpi", "date_ref"), name="uq_valeur_kpi_kpi_date"
                    )
                ],
            },
        ),
    ]
