# Generated by Django 5.1.4 on 2026-09-09 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("direction", "Direction"),
                            ("exploitation", "Exploitation"),
                            ("capitainerie", "Capitainerie"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                (
                    "permissions_kpi",
                    models.BooleanField(
                        default=True, help_text="Peut consulter les KPI"
                    ),
                ),
                (
                    "permissions_analytics",
                    models.BooleanField(
                        default=True, help_text="Peut faire des analyses OLAP"
                    ),
                ),
                (
                    "permissions_alertes",
                    models.BooleanField(
                        default=True, help_text="Peut voir les alertes"
                    ),
                ),
                (
                    "permissions_reporting",
                    models.BooleanField(
                        default=True, help_text="Peut générer des rapports"
                    ),
                ),
                (
                    "permissions_admin",
                    models.BooleanField(
                        default=False, help_text="Accès à l'administration"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profil",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=25)),
                ("poste", models.CharField(blank=True, max_length=100)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "derniere_connexion_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilisateurs",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="JournalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("connexion", "Connexion"),
                            ("deconnexion", "Déconnexion"),
                            ("import_etl", "Import ETL"),
                            ("calcul_kpi", "Calcul KPI"),
                            ("generation_rapport", "Génération rapport"),
                            ("acquittement_alerte", "Acquittement alerte"),
                            ("modification_seuil", "Modification seuil"),
                            ("creation_user", "Création utilisateur"),
                            ("modification_user", "Modification utilisateur"),
                            ("consultation", "Consultation"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "date_action",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("succes", models.BooleanField(default=True)),
                ("objet_type", models.CharField(blank=True, max_length=50)),
                ("objet_id", models.CharField(blank=True, max_length=50)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'action",
                "verbose_name_plural": "Journal des actions",
                "db_table": "journal_action",
                "ordering": ["-date_action"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "date_action"],
                        name="journal_act_utilisa_353efb_idx",
                    ),
                    models.Index(
                        fields=["type_action"], name="journal_act_type_ac_fda64b_idx"
                    ),
                ],
            },
        ),
    ]
