# Generated by Django 5.1.4 on 2026-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("direction", "Direction"),
                    ("exploitation", "Exploitation"),
                    ("capitainerie", "Capitainerie"),
                    ("dapc", "DAPC"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
