# Generated by Django 5.1.4 on 2026-08-19 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etl", "0001_initial"),
        ("referentiel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escale",
            fields=[
                ("id_escale", models.AutoField(primary_key=True, serialize=False)),
                ("date_arrivee", models.DateTimeField()),
                ("date_accostage", models.DateTimeField(blank=True, null=True)),
                ("date_appareillage", models.DateTimeField(blank=True, null=True)),
                ("date_depart", models.DateTimeField(blank=True, null=True)),
                (
                    "temps_attente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="en heures",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "temps_sejour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "temps_pilotage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "temps_accostage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "tonnage_debarque",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tonnage_embarque",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        db_column="id_agent",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escales",
                        to="referentiel.agentmaritime",
                    ),
                ),
                (
                    "date_ref",
                    models.ForeignKey(
                        db_column="id_date",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escales",
                        to="referentiel.calendrier",
                    ),
                ),
                (
                    "import_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escales",
                        to="etl.journalimport",
                    ),
                ),
                (
                    "navire",
                    models.ForeignKey(
                        db_column="id_navire",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escales",
                        to="referentiel.navire",
                    ),
                ),
                (
                    "quai",
                    models.ForeignKey(
                        db_column="id_quai",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escales",
                        to="referentiel.quai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escale",
                "db_table": "escale",
            },
        ),
        migrations.CreateModel(
            name="Mobiliser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duree_reelle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "ordre_intervention",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "escale",
                    models.ForeignKey(
                        db_column="id_escale",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_mobilises",
                        to="escales.escale",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        db_column="id_service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobilisations",
                        to="referentiel.servicenautique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobilisation de service nautique",
                "verbose_name_plural": "Mobilisations de services nautiques",
                "db_table": "mobiliser",
            },
        ),
        migrations.AddIndex(
            model_name="escale",
            index=models.Index(fields=["navire"], name="escale_id_navi_ac70e0_idx"),
        ),
        migrations.AddIndex(
            model_name="escale",
            index=models.Index(fields=["quai"], name="escale_id_quai_c7aad1_idx"),
        ),
        migrations.AddIndex(
            model_name="escale",
            index=models.Index(fields=["date_ref"], name="escale_id_date_7d4bb3_idx"),
        ),
        migrations.AddConstraint(
            model_name="mobiliser",
            constraint=models.UniqueConstraint(
                fields=("escale", "service"), name="uq_mobiliser_escale_service"
            ),
        ),
    ]
