# Generated by Django 5.1.4 on 2026-09-09 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AxeAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("temps_mois", "Mois"),
                            ("temps_trimestre", "Trimestre"),
                            ("temps_annee", "Année"),
                            ("terminal", "Terminal"),
                            ("poste", "Poste"),
                            ("type_navire", "Type de navire"),
                            ("compagnie", "Compagnie maritime"),
                            ("agent", "Agent maritime"),
                            ("statut", "Statut de l'escale"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Axe d'analyse",
                "verbose_name_plural": "Axes d'analyse",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CubeAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "mesure",
                    models.CharField(
                        choices=[
                            ("nb_escales", "Nombre d'escales"),
                            ("nb_arrivees", "Nombre d'arrivées"),
                            ("nb_departs", "Nombre de départs"),
                            ("temps_attente_moy", "Temps d'attente moyen (h)"),
                            ("temps_sejour_moy", "Temps de séjour moyen (h)"),
                            ("temps_pilotage_moy", "Temps de pilotage moyen (h)"),
                            ("taux_occupation", "Taux d'occupation des postes (%)"),
                            ("tonnage_total", "Tonnage total manutentionné (t)"),
                            ("productivite", "Productivité (t/escale)"),
                            ("taux_ponctualite", "Taux de ponctualité (%)"),
                            ("taux_congestion", "Taux de congestion (%)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "axe_colonne",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dimension portée par les colonnes (optionnel — analyse 1D si absent)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cubes_colonne",
                        to="analytics.axeanalyse",
                    ),
                ),
                (
                    "axe_ligne",
                    models.ForeignKey(
                        help_text="Dimension portée par les lignes du tableau croisé",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cubes_ligne",
                        to="analytics.axeanalyse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cube d'analyse",
                "verbose_name_plural": "Cubes d'analyse",
                "ordering": ["mesure", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ResultatCube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField()),
                (
                    "mois_debut",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-12, null = année entière", null=True
                    ),
                ),
                (
                    "mois_fin",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-12, null = année entière", null=True
                    ),
                ),
                (
                    "donnees",
                    models.JSONField(
                        help_text="Résultat sérialisé du cube (liste de dicts)"
                    ),
                ),
                ("nb_lignes", models.PositiveIntegerField(default=0)),
                (
                    "date_calcul",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="analytics.cubeanalyse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de cube",
                "verbose_name_plural": "Résultats de cube",
                "ordering": ["-date_calcul"],
                "indexes": [
                    models.Index(
                        fields=["cube", "annee", "mois_debut", "mois_fin"],
                        name="analytics_r_cube_id_241491_idx",
                    )
                ],
            },
        ),
    ]
